const product = {
  Products: [
    {
      id: 1,
      name: "Panda Soft Teddy ",
      image: "/images/product1.png",
      price: 3599,
      age: "2",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 2,
      name: "Peppa Pig",
      image: "/images/product2.png",
      price: 839,
      age: "5",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 3,
      name: "Babyhug Teddy",
      image: "/images/product3.png",
      price: 1010,
      age: "2",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 4,
      name: "Funzoo Elephant",
      image: "/images/product4.png",
      price: 278,
      age: "8",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 5,
      name: "Bunny Soft Toy",
      image: "/images/product5.png",
      price: 341,
      age: "8",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 6,
      name: "Plush Elephant Soft Toy",
      image: "/images/product6.png",
      price: 851,
      age: "4",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 7,
      name: "Happy Elephant Soft Toy",
      image: "/images/product7.png",
      price: 303,
      age: "5",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 8,
      name: "Baby Shark",
      image: "/images/product8.png",
      price: 2483,
      age: "8",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 9,
      name: "BabyCat Soft Toy",
      image: "/images/offer1.png",
      price: 699,
      age: "4",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 10,
      name: "Cute Lion Baby Toy",
      image: "/images/offer2.png",
      price: 599,
      age: "4",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 11,
      name: "White Dog Soft Toy",
      image: "/images/product11.png",
      price: 596,
      age: "5",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
    {
      id: 12,
      name: "Baby Penguin Soft Toy",
      image: "/images/product12.png",
      price: 899,
      age: "2",
      quantity: 1,
      wishlist: 0,
      add: 0,
    },
  ],
};
export default product;
